# Algortihm Parameters
ML:
  seed: 0
  obs_dim: 44
  n_act: 6
  epochs: 10
  hdim: 64
  policy_lr: 1e-3
  value_lr: 1e-3
  max_std: 1.0
  clip_range: 0.2
  n_step: 16 # 1000

  gamma: 0.99
  lam: 0.98
  episode_size: 1
  batch_size: 16
  nupdates: 1000

  act_step: 1 # 30
  sub_step: 30
  save_step: 10
  maxlen_num: 10

# Input type
control_type: traj_pos #traj_vel or vel or pos or traj_pos

# Limit
force_limit1: 15 # 15 when using only wrist_3
torque_limit1: 2 #  2 when using only wrist_3
force_limit2: 30 # 300 ~ over 1000 in position control
torque_limit2: 4 # 30 ~  in position control
min_static_limit: -0.4 # -0.1 when using only wrist_3
max_static_limit:  0.4 #  0.1 when using only wrist_3

# act
act_params:
 dt_act: 0.5
 dt_reset: 1

# normarizing parameters for observations
obs_params:
  joint_n: 1
  eef_n: 10
  eef_rpy_n: 1
  force_n: 1 # 0.01
  torque_n: 1 # 0.1
  taxel_n: 0.0003 # 0.01

observations: # Observations you want to use for the learning
  - shp_joint_ang # 6
  - shl_joint_ang
  - elb_joint_ang
  - wr1_joint_ang
  - wr2_joint_ang
  - wr3_joint_ang
  - shp_joint_vel # 6
  - shl_joint_vel
  - elb_joint_vel
  - wr1_joint_vel
  - wr2_joint_vel
  - wr3_joint_vel
  - eef_x # 3
  - eef_y
  - eef_z
  - eef_rpy_x # 3
  - eef_rpy_y
  - eef_rpy_z
  - force_x # 3
  - force_y
  - force_z
  - torque_x # 3
  - torque_y
  - torque_z
  - image_cnn # 20
#  - static_taxel # 56
#  - dynamic_taxel

joint_names: ['shoulder_link', 'upper_arm_link', 'forearm_link', 'wrist_1_link', 'wrist_2_link', 'wrist_3_link']

#init_joint_pose0:
#  shp: 1.55
#  shl: -1.81
#  elb: 2.26
#  wr1: -2.02
#  wr2: -1.57
#  wr3: 3.11

init_joint_pose1:
  shp: 1.4410264033536153
  shl: -1.6883855417730604
  elb: 2.6771635884219136
  wr1: 2.1674968289716623
  wr2: -1.4199836765311638
  wr3: 1.5702616267031195

init_joint_pose2:
  shp: 1.4914358562995678
  shl: -1.4309883592541488
  elb: 2.4144281080217893
  wr1: 2.1727191706904554
  wr2: -1.4692292654987007
  wr3: 1.5707477068653029

far_pose:
  shp: 1.4410264033536153
  shl: -1.6883855417730604
  elb: 2.6771635884219136
  wr1: 2.1674968289716623
  wr2: -1.4199836765311638
  wr3: 1.5702616267031195

before_close_pose:
  shp: 1.5857990679615237
  shl: -1.5611849786259067
  elb: 2.550973234715942
  wr1: 2.151942347671375
  wr2: -1.5845770347385386
  wr3: 1.5712500016837836

close_door_pose:
  shp: 1.4974456350976515
  shl: -1.3815174788448505
  elb: 2.3492944464703363
  wr1: 2.1884996025671186
  wr2: -1.4775036417585037
  wr3: 1.5706990988490845

init_grp_pose1: 0
init_grp_pose2: 120

joint_limits_array:
  shp_max: 3.14
  shp_min: -3.14
  shl_max: 3.14
  shl_min: -3.14
  elb_max: 3.14
  elb_min: -3.14
  wr1_max: 3.14
  wr1_min: -3.14
  wr2_max: 3.14
  wr2_min: -3.14
  wr3_max: 3.14
  wr3_min: -3.14

joint_velocity_limits_array:
  shp_max: 1.0
  shp_min: -1.0
  shl_max: 1.0
  shl_min: -1.0
  elb_max: 1.0
  elb_min: -1.0
  wr1_max: 1.0
  wr1_min: -1.0
  wr2_max: 1.0
  wr2_min: -1.0
  wr3_max: 1.0
  wr3_min: -1.0

cartesian_limits:  # default #On the surface plate
  x_max: -0.08     # -0.08   #  0.2
  x_min: -0.10     # -0.11   # -0.45
  y_max: 0.425     #  0.425  #  0.7
  y_min: 0.35      #  0.35   # -0.25
  z_max: 0.29      #  0.31   #  2
  z_min: 0.27      #  0.26   #  0.15

#episode_done_criteria:
#  - panel_10deg

  #- minimum_height
  #- monoped_vertical_orientation
